# Generated by Django 5.2.9 on 2025-12-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='ability_image_url',
        ),
        migrations.RemoveField(
            model_name='gameuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='hero_image_url',
        ),
        migrations.AddField(
            model_name='hero',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='heroes/'),
        ),
    ]
